### ISSUE TITLE
Error processing "disconnect": TypeError: Cannot read property 'noDebug' of undefined

### ISSUE THREAD

**Issue by osricwong** [Microsoft/vscode-node-debug2#149]
Hello, when i try to run `Debug Android` from `Debug` after vscode update,
I got the following error message on debug console window.

```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.17.3
Could not debug. Unknown error
Error processing "disconnect": TypeError: Cannot read property 'noDebug' of undefined
    at Object.terminateSession (/Users/ks/.vscode/extensions/ms-vscode.node-debug2-1.18.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:198:63)
    at Object.terminateSession (/Users/ks/.vscode/extensions/ms-vscode.node-debug2-1.18.3/out/src/nodeDebugAdapter.js:400:15)
    at Object.disconnect (/Users/ks/.vscode/extensions/ms-vscode.node-debug2-1.18.3/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:821:21)
    at Object.dispatchRequest (/Users/ks/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugSession.js:75:82)
    at Object.disconnect (/Users/ks/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/debugger/nodeDebugWrapper.js:83:23)
    at Object.dispatchRequest (/Users/ks/.vscode/extensions/vsmobile.vscode-react-native-0.4.4/src/debugger/nodeDebugWrapper.js:44:29)
```

VSCode version 1.17.2

Thank you in advance for your answers.

**Comment by roblourens** [comment]
Can you post your launch config?

**Comment by osricwong** [comment]
sure :)

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "target": "iPhone 5s",
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "name": "Debug Android 2",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "noDebug": false,
            "outDir": "${workspaceRoot}/.vscode/.react"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

the error is shown when i tried to run `Debug Android` or `Debug Android 2`.

Thanks.

**Comment by roblourens** [comment]
I think the real problem is `Could not debug. Unknown error` which is coming from the reactnative extension, so please file your issue on their repo. But I see the error from node2 and can fix that.

**Comment by osricwong** [comment]
I might check from `vscode-react-native` repo first.
thanks :)
