### ISSUE TITLE
The debug adapter crashes when starting an extension debug session

### ISSUE THREAD

**Issue by Marwes** [Microsoft/vscode-node-debug2#159]
Getting this crash when trying to debug https://github.com/gluon-lang/gluon_language-server/pull/15/commits/da1b5b9341ffed30cbd4e6a6d257d6618b26bfd5 . 

Stacktrace from VS code's debug console.

```
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: patterns.forEach is not a function
    at Object.multiGlob (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:341:18)
    at EagerSourceMapTransformer.init (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\eagerSourceMapTransformer.js:26:39)
    at EagerSourceMapTransformer.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:37:14)
    at NodeDebugAdapter.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:164:36)
    at NodeDebugAdapter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:205:40)
    at Generator.next (<anonymous>)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:10:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:6:12)
    at NodeDebugAdapter.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.no[...]
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: patterns.forEach is not a function
    at Object.multiGlob (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:341:18)
    at EagerSourceMapTransformer.init (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\eagerSourceMapTransformer.js:26:39)
    at EagerSourceMapTransformer.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:37:14)
    at NodeDebugAdapter.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:164:36)
    at NodeDebugAdapter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:205:40)
    at Generator.next (<anonymous>)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:10:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:6:12)
    at NodeDebugAdapter.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.no[...]
******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: patterns.forEach is not a function
    at Object.multiGlob (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:341:18)
    at EagerSourceMapTransformer.init (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\eagerSourceMapTransformer.js:26:39)
    at EagerSourceMapTransformer.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:37:14)
    at NodeDebugAdapter.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:164:36)
    at NodeDebugAdapter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:205:40)
    at Generator.next (<anonymous>)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:10:71
    at Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:6:12)
    at NodeDebugAdapter.attach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.no[...]
```

```
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

Let me know if more information is needed.

**Comment by roblourens** [comment]
Can I see your launch config?

**Comment by Marwes** [comment]
> Can I see your launch config?

I can post it tonight but it is just a unmodified config that VS Code generated. I had an older config generated way back so I figured that could be the case but although the freshly generated one changed slightly the same issue persists.

**Comment by roblourens** [comment]
The error implies that there's something weird about the `outFiles` property, so I'd like to see the one you used to get that error.

**Comment by Marwes** [comment]
```
		{
			"type": "extensionHost",
			"request": "launch",
			"name": "Launch Extension",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "npm"
		},
```

**Comment by Marwes** [comment]
Seems like the generated .js files end up in `out/src`, `out/src/src` and `out/src/debugger`

**Comment by roblourens** [comment]
That looks totally normal... could you set `"trace": true` in the launch config, run it again to get the error, and upload the log here? (it prints the log path in the debug console)

**Comment by Marwes** [comment]
I deleted `out` so it were created from scratch and now I no longer get this error.

What I believe happened is that I had some really old generated `.js` files in `out/src/src` which were left from an earlier version of `VSCode`/`Typescript`/`vscode-node-debug`. Since these files had the same names as the actual files found under `out/src` they somehow broke `vscode-node-debug`...

**Comment by Marwes** [comment]
I just tried restoring `out` to the original files and now I can't reproduce this anymore even.

**Comment by roblourens** [comment]
Hm, I'm not sure how that would impact it because the error stack shows it crashing before executing the glob or looking at the files at all. The error implies that `outFiles` is not an array, which seems impossible.

I'll close it for now, but if you see it again I'd really like to have a log.
