### ISSUE TITLE
Starting babel.js project with breakpoints throws exception.

### ISSUE THREAD

**Issue by mrukas** [Microsoft/vscode-node-debug2#78]
I'm using **babel-register** with **transform-async-to-generator** in a project. If i'm using **node2** as debugger, exceptions are getting thrown if breakpoints are set during start.

This is the exception:
`******** Unhandled error in debug adapter - Unhandled promise rejection: TypeError: Column must be greater than or equal to 0, got -1
    at SourceMapConsumer_findMapping [as _findMapping] (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/source-map/lib/source-map-consumer.js:543:13)
    at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/source-map/lib/source-map-consumer.js:748:22)
    at SourceMap.generatedPositionFor (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:159:34)
    at SourceMaps.mapToGenerated (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMaps.js:28:18)
    at args.breakpoints.forEach.bp (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:63:53)
    at Array.forEach (native)
    at EagerSourceMapTransformer.setBreakpoints (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/transformers/baseSourceMapTransformer.js:61:34)
    at validateBreakpointsPath.then (/usr/share/code-insiders/resources/app/extensions/ms-vscode.node-debug2/node_modules/vscode-chrome-debug-core/out/src/[...]`

This only happens when using **node2**. The old **node** debugger works fine. This seems to be a problem using the generated sourcemaps of babel.js.

Here is a example project to test it: [https://github.com/mrukas/koa-babel-test/tree/master](https://github.com/mrukas/koa-babel-test/tree/master)

The **master** branch uses the new debugger and the **old-debug** branch uses the old debugger.

**Comment by roblourens** [comment]
Thanks for the sample project. I remember someone else reporting this error before but couldn't give a repro. I'll try it out
